//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

use crate::entity::language_model_config;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "agent")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub language_model_config_id: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "language_model_config_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub language_model_config: HasOne<super::language_model_config::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}

